# Generated by Django 5.1 on 2024-09-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
