# Generated by Django 5.1 on 2024-09-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_token_id_alter_token_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expires_at',
        ),
    ]
